name: Angular CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build Angular (Production)
        run: npm run build -- --configuration production

      - name: Run Tests
        run: npm run test:ci --if-present
      - name: Build Docker Image
        run: |
           docker build -t habibulla/airesumeimagefrontend:${{ github.sha }} .
           docker tag habibulla/airesumeimagefrontend:${{ github.sha }} habibulla/airesumeimagefrontend:latest
      - name: Login into Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Image
        run: |
           docker push habibulla/airesumeimagefrontend:${{ github.sha }}
           docker push habibulla/airesumeimagefrontend:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH for EC2
      uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
      with:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        EC2_URL: ${{ secrets.EC2_URL }}
    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_URL }} "
          cd /opt &&
             docker compose pull &&
             docker compose up -d &&
             docker image prune -af 
        "

